
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'coma identificador numero pderecho pizquierdo punto_y_comaprograma : instruccionesinstrucciones : instruccion instrucciones\n                     | emptyinstruccion : identificador operandos punto_y_comaoperandos : elemento coma operandos\n                 | elementoelemento : numeroelemento : identificadorelemento : emptyempty : '
    
_lr_action_items = {'coma':([1,6,8,9,10,13,],[-10,-8,-7,-9,13,-10,]),'identificador':([0,1,4,12,13,],[1,6,1,-4,6,]),'punto_y_coma':([1,6,7,8,9,10,13,14,],[-10,-8,12,-7,-9,-6,-10,-5,]),'numero':([1,13,],[8,8,]),'$end':([0,2,3,4,5,11,12,],[-10,-1,0,-10,-3,-2,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instrucciones':([0,4,],[2,11,]),'instruccion':([0,4,],[4,4,]),'operandos':([1,13,],[7,14,]),'programa':([0,],[3,]),'empty':([0,1,4,13,],[5,9,5,9,]),'elemento':([1,13,],[10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> instrucciones','programa',1,'p_programa','sintaxis.py',6),
  ('instrucciones -> instruccion instrucciones','instrucciones',2,'p_instrucciones','sintaxis.py',12),
  ('instrucciones -> empty','instrucciones',1,'p_instrucciones','sintaxis.py',13),
  ('instruccion -> identificador operandos punto_y_coma','instruccion',3,'p_instruccion','sintaxis.py',22),
  ('operandos -> elemento coma operandos','operandos',3,'p_operandos','sintaxis.py',30),
  ('operandos -> elemento','operandos',1,'p_operandos','sintaxis.py',31),
  ('elemento -> numero','elemento',1,'p_elemento_numerico','sintaxis.py',40),
  ('elemento -> identificador','elemento',1,'p_elemento_identificador','sintaxis.py',48),
  ('elemento -> empty','elemento',1,'p_elemento_vacio','sintaxis.py',56),
  ('empty -> <empty>','empty',0,'p_empty','sintaxis.py',60),
]
